name: Auto Update DMM Site

on:
  schedule:
    - cron: "0 18 * * *"  # 毎日日本時間3時に実行（UTC+9なので18時）
  workflow_dispatch:      # 手動実行も可能

jobs:
  build:
    runs-on: ubuntu-latest

    env:                     # Secrets を環境変数として渡す
      DMM_API_ID: ${{ secrets.DMM_API_ID }}
      DMM_AFF_ID: ${{ secrets.DMM_AFF_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests jinja2
      - name: Run update.py
        run: python3 update.py
      
      - name: Check output folder
        run: ls -R output
